documentation:
- changed-files:
  - any-glob-to-any-file: 'docs/**'

backend:
- changed-files:
  - any-glob-to-any-file: 'backend/**'

frontend:
- changed-files:
  - any-glob-to-any-file: 'frontend/**'
