/**
 * StudyConnect Backend API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateGroupRequest {
    name?: string;
    description?: string;
    is_public?: boolean;
    member_ids?: Array<number>;
    admin_ids?: Array<number>;
}
