/**
 * StudyConnect Backend API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreateRequest {
    firstname: string;
    lastname: string;
    /**
     * Must include uppercase, lowercase, digit, and special character.
     */
    password: string;
    email: string;
}
